---
title: "Reproducibility: Setting Up"
author: Zachary del Rosario
date: 2020-06-24
output: github_document
time: 10
reading: 0
---

*Purpose*: We're going to need a lot of tools to make it through this class, you and I. This pre-class exercise will get you signed up for all the (free) accounts you'll need for the class.

*Reading*: (None)

*Topics*: GitHub, Discord, Fandom

# Setup
<!-- -------------------------------------------------- -->

## Git
<!-- ------------------------- -->

Git is free and open-source version control software. One of our desired outcomes from this course is to learn how to use git to rigorously track our data science work. Install Git, following the instructions relevant to your operating system:

- (Mac OS) If you attempt to run `git` from the Terminal and don't have it installed, Mac OS should automatically start the installation. [See here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) for more info.
- (Windows) Install [Git for Windows](https://gitforwindows.org/)
- (Linux) Use your favorite package manager and install `git`. [See here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) fore more info.

## GitHub
<!-- ------------------------- -->

GitHub is a free service that helps you track and share code, interfacing with Git. We will use this to distribute and submit assignments.

- You will need an account on [GitHub](https://github.com/); create an account and share your username in the survey below.

## Discord
<!-- ------------------------- -->

Discord is a free service used for communication. It's like a combination of Slack (persistent text channels) and Zoom (audio and video chat). We will use this for almost all communication about the class, including technical questions, office hours, and (online) class sessions.

- You will need an account on [Discord](https://discord.com/); create an account and share your username in the survey below.

## Fandom
<!-- ------------------------- -->

Fandom is a free service used for community Wiki's, much like Wikipedia. I have created an [Olin Data Science Wiki](https://olin-data-science.fandom.com/wiki/Olin_Data_Science_Wiki); we will fill this in together with our data science findings. This is required, as group deliverables will be recorded in our Wiki.

- You will need an account on [Fandom](https://www.fandom.com/register?redirect=https%3A%2F%2Fwww.fandom.com%2F); create an account.

# Record Your Info
<!-- -------------------------------------------------- -->

In order to fully enroll you in the course, I need some information. Please fill out [this survey](https://forms.gle/uyHKHh81TWthdUR66) once you've created all the accounts mentioned above.

<!-- include-exit-ticket -->
