---
title: "RStudio: Shortcuts"
author: Zachary del Rosario
date: 2020-05-07
output: github_document
time: 10
reading: 5
---

*Purpose*: Your ability to get stuff done is highly dependent on your fluency
with your tools. One aspect of fluency is knowing and *using* keyboard
shortcuts. In this exercise, we'll go over some of the most important ones.

*Reading*: [Keyboard
shortcuts](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts); [Code Chunk Options](https://rmarkdown.rstudio.com/lesson-3.html)
*Note*: Use this reading to look up answers to the questions below. Rather than
*memorizing* this information, I recommend you download a
[cheatsheet](https://rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf),
and either print it out or save it in a convenient place on your computer. Get
used to referencing your cheatsheets while doing data science---practice makes
perfect!

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = TRUE)
```

__q1__ What do the following keyboard shortcuts do?

* Within the script editor or a chunk

    * `Alt` + `-`

        <!-- solution-begin -->
        Insert assignment operator `<-`
        <!-- solution-end -->

    * `Shift` + `Cmd/Ctrl` + `M`

        <!-- solution-begin -->
        Insert pipe operator `%>%`
        <!-- solution-end -->

    * `Cmd/Ctrl` + `Enter`

        <!-- solution-begin -->
        If no text is highlighted, run complete expression that cursor is
        on, and advance to the next line. If text is highlighted, run
        selected text.
        <!-- solution-end -->

    * `F1` (Note: on a Mac you need to press `fn` + `F1`)

        <!-- solution-begin -->
        If cursor is on a function name, pull up the help page for the function.
        <!-- solution-end -->

	* `Cmd/Ctrl` + `Shift` + `C`

        <!-- solution-begin -->
		Comment/uncomment the code at the cursor, or highlighted code.
        <!-- solution-end -->


* Within R Markdown

    * `Cmd/Ctrl` + `Alt` + `I`

        <!-- solution-begin -->
        Insert chunk.
        <!-- solution-end -->

* Within a chunk

    * `Shift` + `Cmd/Ctrl` + `Enter`

        <!-- solution-begin -->
        Run current chunk.
        <!-- solution-end -->

__q2__ For a chunk, what header option do you use to

* Run the code, don't display it, but show its results?

    <!-- solution-begin -->
    `echo=FALSE`
    <!-- solution-end -->

* Run the code, but don't display it or its results?

    <!-- solution-begin -->
    `include=FALSE`
    <!-- solution-end -->

__q3__ How do stop the code in a chunk from running once it has started?

<!-- solution-begin -->
Click the red square in the top right corner of the chunk.
<!-- solution-end -->

<!-- include-exit-ticket -->
