---
title: "Make Schedules"
author: "ZDR"
date:
output:
  github_document
---

# Setup

```{r setup}
library(tidyverse)
library(lubridate)
filename_dep <- "./schedule.csv"
filename_exercises <- "./schedule_exercises.csv"
filename_challenges <- "./schedule_challenges.csv"
```

## Schedule dependency data

```{r make-schedule}
## Define schedule
df_schedule <-
  tribble(
    ~name,                           ~day, ~challenge,
    "e-comm00-style",                   3,  0,
    "e-comm01-responding",              5,  1,
    "e-comm02-story-basics",           22,  4,

    "e-data00-basics",                  2,  0,
    "e-data01-isolate",                 7,  1,
    "e-data02-derive",                  9,  2,
    "e-data03-pivot-basics",           13,  2,
    "e-data04-separate-unite",         17,  3,
    "e-data05-join",                   20,  4,
    "e-data06-strings",                23,  4,
    "e-data07-placeholders",           25,  5,
    "e-data08-window",                 27,  5,
    "e-data09-readxl",                 29,  5,
    "e-data10-map",                    31,  6,
    "e-data11-factors",                32,  6,
    "e-data12-simple-pipeline",        33,  6,
    "e-data13-cleaning",               43,  9,
    "e-data14-webplotdigitizer",       45, 10,
    "e-data15-tabula",                 46, 10,

    "e-setup00-install",                0,  0,
    "e-setup01-packages",               1,  0,
    "e-setup02-functions",              1,  0,
    "e-setup03-docs",                   2,  0,
    "e-setup04-rstudio-shortcuts",      3,  0,
    "e-setup05-vectors",                4,  0,
    "e-setup06-types",                  4,  0,

    "e-rep00-setup",                    0,  0,
    "e-rep01-intro-git",                0,  0,
    # "e-rep02-create",                   1,  0,
    "e-rep03-track",                    1,  0,
    "e-rep04-directories",             11,  2,
    "e-rep05-collab",                  14,  2,

    "e-stat00-eda-basics",              6,  1, 
    "e-stat01-densities",              12,  2,
    "e-stat02-probability",            16,  3,
    "e-stat03-descriptive",            19,  3,

    "e-stat04-population",             28,  6,
    "e-stat05-inference",              30,  6,
    "e-stat06-moment",                 34,  7,
    "e-stat07-clt",                    35,  7,
    "e-stat08-error-bias",             37,  8,
    "e-stat09-hyp-intro",              38,  8,
    "e-stat10-randomization",          39,  8,
    "e-stat11-ci-pi",                  40,  8,
    "e-stat12-fit-dist",               41,  8,

    "e-model00-source",                42,  8,
    "e-model01-intro",                 47, 11,
    "e-model02-train-validate",        48, 11,
    "e-model03-interp-warnings",       50, 11,
    "e-model04-logistic",              52, 12,
    "e-model05-roc",                   53, 12,

    "e-vis00-basics",                   5,  1,
    "e-vis01-bar-charts",               8,  1,
    "e-vis02-histograms",              10,  2,
    "e-vis03-boxplots",                15,  3,
    "e-vis04-scatterplot",             18,  3,
    "e-vis05-lines",                   21,  4,
    "e-vis06-themes",                  24,  4,
    "e-vis07-perception",              26,  5,
    "e-vis08-multiples",               36,  7,
    "e-vis09-improve",                 44,  9,
    "e-vis10-control-chart",           54,  12,
    # Placeholders needed for challenge scheduling
    NA_character_,                     55,  12,
  )

df_schedule %>% 
  filter(!is.na(name)) %>% 
  select(name, day) %>% 
  write_csv(filename_dep)
```

## Class metadata

```{r metadata}
# Bounds
date_start <- ymd("2025-01-23") # First day of class
date_end <- ymd("2025-04-30")   # Last day of class

# Class days
# Sunday==1, Monday==2, Tuesday==3, Wednesday==4, Thursday==5, Friday==6, Saturday==7
wday_class <- c(2, 5)

# Holidays
df_holidays <- tribble(
  ~date, ~comment,
  # ymd("2024-02-17"), "Winter break",
  ymd("2025-02-17"), "President's day",
  ymd("2025-03-17"), "Spring break",
  ymd("2025-03-18"), "Spring break",
  ymd("2025-03-19"), "Spring break",
  ymd("2025-03-20"), "Spring break",
  ymd("2025-03-21"), "Spring break",
  ymd("2025-04-21"), "Patriots' day",
)

# Extra days added by the registrar
df_extras <- tribble(
  ~date, ~comment,
  ymd("2023-02-19"), "Olin Monday",
  ymd("2023-04-22"), "Olin Monday",
)

```


# Assign

## Instructional days

```{r}
df_instructional <- 
  tibble(date = seq(date_start, date_end, by = "days")) %>% 
  ## Remove invalid days
  filter(
    # No weekends
    !(wday(date) %in% c(1, 7)) # Sat., Sun.
  ) %>% 
  # No holidays
  anti_join(df_holidays) %>% 
  # Assign `day` number
  rowid_to_column(var = "day") %>% 
  mutate(day = day - 1) %>% 
  ## Assign exercises
  left_join(df_schedule)

# Show all the data
df_instructional

## Write to file
df_instructional %>% 
  filter(!is.na(name)) %>% 
  select(date, exercise = name) %>% 
  write_csv(filename_exercises)
```

## Class days

Used to assign challenge due dates, based on exercise dependencies

```{r}
df_challenges <- 
  df_instructional %>% 
  # Collapse exercises
  distinct(day, date, challenge) %>% 
  # Take valid class days only
  filter(
    (wday(date) %in% wday_class) | (date %in% df_extras$date)
  ) %>% 
  # Compute class days
  mutate(day_class = consecutive_id(day)) %>% 
  # Lag to ensure exercise completion
  mutate(challenge = lag(challenge)) %>% 
  # Latest possible due-date given constraints
  group_by(challenge) %>% 
  filter(day == max(day)) %>% 
  ungroup() %>% 
  
  filter(!is.na(challenge))

## Write to file
df_challenges %>% 
  select(date, challenge) %>% 
  write_csv(filename_challenges)

df_challenges 
```


## Quality checks

### Class Day

```{r}
# Count exercises on each date
df_instructional %>% 
  ggplot(aes(day)) +
  geom_bar() +
  geom_vline(
    data = df_challenges,
    mapping = aes(xintercept = day)
  ) +
  geom_label(
    data = df_challenges,
    mapping = aes(x = day, y = 4, label = challenge)
  ) +
  scale_x_continuous(breaks = seq(1, 70, by = 2))

```

### Calendar date

```{r}
# Count exercises on each date
df_instructional %>% 
  filter(!is.na(name)) %>% 
  ggplot(aes(date)) +
  # Special dates
  geom_vline(
    xintercept = date_start,
    color = "blue", linewidth = 1.5
  ) +
  geom_vline(
    xintercept = date_end,
    color = "blue", linewidth = 1.5
  ) +
  geom_vline(
    data = df_holidays,
    mapping = aes(xintercept = date),
    color = "salmon", linewidth = 1.5
  ) +
  # Challenge min deadline
  geom_vline(
    data = df_challenges,
    mapping = aes(xintercept = date)
  ) +
  geom_label(
    data = df_challenges,
    mapping = aes(x = date, y = 4, label = challenge)
  ) +
  # Exercise count
  geom_bar() +
  
  scale_x_date(
    date_labels = "%b %d",
    limits = c(date_start - day(1), date_end + day(1))
  )
```