---
title: "Visualize Curriculum Metadata"
author: "Zach"
date: 2020-06-08
output:
  github_document
---

# Setup
<!-- -------------------------------------------------- -->

```{r script-setup}
library(tidyverse)
library(NCmisc)
library(ggrepel)

## Filenames
filename_seq <- "../sequence.md"

## Data directory
exercise_data <- "~/Git/data-science-curriculum/exercises"

df_ex_files <-
  tibble(file = list.files(exercise_data, full.names = TRUE)) %>%
  filter(str_detect(file, "Rmd$")) %>%
  mutate(
    filename = str_extract(file, "[^/]+\\.Rmd"),
    name = str_remove(filename, "(-master)?\\.Rmd")
  )

## Flatten function list
flatten_funs <- function(l) {
  res <- c()

  if (length(l) > 0) {
    for (i in 1:length(l)) {
      res <- c(res, l[[i]])
    }

    res
  } else{
    NA_character_
  }
}
```

Parse all exercise files; determine functions used and read metadata.

```{r load-exercises, echo=FALSE, message=FALSE}
df_exercises <-
  pmap_dfr(
    df_ex_files,
    function(file, filename, name) {
      ## Render R file for function discovery
      fileR <- str_replace(file, "Rmd", "R")
      knitr::purl(file, output = fileR)
      funs <- list.functions.in.file(fileR, alphabetic = TRUE)
      ## Delete temporary R file
      unlink(fileR)

      ## Parse Rmd file yaml
      df_result <-
      rmarkdown::yaml_front_matter(file) %>%
        as_tibble() %>%
        mutate(
          total = time + reading,
          name = name,
          catnum = str_extract(name, "[:alpha:]+\\d+"),
          functions = list(flatten_funs(funs))
        ) %>%
        extract(
          col = catnum,
          into = c("category", "number"),
          regex = "([:alpha:]+)(\\d+)",
          convert = TRUE
        )
    }
  )
```

# Scheduling
<!-- -------------------------------------------------- -->

Schedule the exercise curriculum

```{r schedule}
## Define schedule
df_schedule <-
  tribble(
    ~name,                           ~day,
    "e-comm00-style",                   2,
    "e-comm01-story-basics",           20,

    "e-data00-basics",                  3,
    "e-data01-isolate",                 5,
    "e-data02-derive",                  7,
    "e-data03-pivot-basics",           10,
    "e-data04-separate-unite",         13,
    "e-data05-join",                   16,
    "e-data06-strings",                19,

    "e-setup00-install",                0,
    "e-setup01-packages",               1,
    "e-setup02-functions",              1,
    "e-setup03-docs",                   3,
    "e-setup04-rstudio-shortcuts",      3,
    "e-setup05-vectors",                3,
    "e-setup06-types",                  3,

    "e-rep00-setup",                    0,
    "e-rep01-intro-git",                0,
    "e-rep02-create",                   1,
    "e-rep03-track",                    1,

    "e-stat00-eda-basics",              4,
    "e-stat01-distributions",           9,
    "e-stat02-probability",            12,
    "e-stat03-descriptive",            15,
    "e-stat04-population",             18,
    "e-stat05-moment",                 19,
    "e-stat06-clt",                    20,

    "e-vis00-basics",                   2,
    "e-vis01-bar-charts",               6,
    "e-vis02-histograms",               8,
    "e-vis03-boxplots",                11,
    "e-vis04-scatterplot",             14,
    "e-vis05-lines",                   17,

  )

## Compute day totals
df_day_totals <-
  left_join(
    df_exercises,
    df_schedule,
    by = "name"
  ) %>%
  group_by(day) %>%
  mutate(day_mins = sum(total)) %>%
  select(name, day, total, day_mins) %>%
  arrange(day)

df_day_totals %>%
  knitr::kable()
```

### Markdown schedule
<!-- ------------------------- -->

```{r md-schedule}
## Format table as string
string_table <-
  df_day_totals %>%
  rename(
    Filename = name,
    Day = day,
    `Exercise Duration (minutes)` = total,
    `Day Duration (minutes)` = day_mins
  ) %>%
  knitr::kable(format = "markdown") %>%
  c(.)

## Write schedule file
writeLines(string_table, filename_seq)
```

### Visual schedule
<!-- ------------------------- -->

Visualize schedule

```{r vis-schedule}
left_join(
  df_exercises,
  df_schedule,
  by = "name"
) %>%
  filter(!str_detect(category, "setup")) %>%

  ggplot(aes(category, day)) +
  geom_label(
    aes(label = name, fill = category)
  ) +

  scale_y_reverse() +
  guides(fill = "none") +
  theme_minimal() +
  labs(
    x = "Category",
    y = "Day",
    title = "Exercise Curriculum"
  )

```

# Summaries
<!-- -------------------------------------------------- -->

Total exercise time, in hours

```{r exercise-time}
df_exercises %>%
  mutate(across(c(time, reading, total), ~ . / 60)) %>%
  summarize(across(c(time, reading, total), sum)) %>%
  knitr::kable()
```

Exercise time, by category

```{r exercise-category-time}
df_exercises %>%
  group_by(category) %>%
  mutate(across(c(time, reading, total), ~ . / 60)) %>%
  summarize(across(c(time, reading, total), sum)) %>%
  knitr::kable()
```

Visualize

```{r exercise-times}
df_exercises %>%
  select(name, category, exercise = time, reading) %>%
  pivot_longer(
    names_to = "type",
    values_to = "time",
    c(exercise, reading)
  ) %>%

  ggplot(aes(name, time, fill = type)) +
  geom_col() +
  coord_flip() +
  facet_grid(category~., scales = "free_y")
```

# Function reference
<!-- -------------------------------------------------- -->

Generate a list of all exercises where each function is used:

```{r fun-ref}
df_funs <-
  df_exercises %>%
  unnest(functions) %>%
  rename(fun = functions) %>%
  select(fun, name) %>%
  arrange(fun)
```
