---
title: "Reproducibility: Setting Up"
author: Zachary del Rosario
date: 2020-06-24
output: github_document
time: 10
reading: 0
---

# Reproducibility: Setup

*Purpose*: We're going to need a lot of tools to make it through this class, you and I. This pre-class exercise will get you signed up for all the (free) accounts you'll need for the class.

*Reading*: (None)

*Topics*: GitHub, Discord

*Note*: If you're reading this file in RStudio, you can Shift + Click (CMD + Click) to follow a link.

## Setup
<!-- -------------------------------------------------- -->

## Git
<!-- ------------------------- -->

Git is free and open-source version control software. One of our desired outcomes from this course is to learn how to use git to rigorously track our data science work. Install Git, following the instructions relevant to your operating system:

- (Mac OS) If you attempt to run `git` from the Terminal and don't have it installed, Mac OS should automatically start the installation. [See here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) for more info.
- (Windows) Install [Git for Windows](https://gitforwindows.org/)
- (Linux) Use your favorite package manager and install `git`. [See here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) for more info.

## GitHub
<!-- ------------------------- -->

GitHub is a free service that helps you track and share code, interfacing with Git. We will use this to distribute and submit assignments.

- You will need an account on [GitHub](https://github.com/).

## Discord
<!-- ------------------------- -->

Discord is a free service used for communication. It's like a combination of Slack (persistent text channels) and Zoom (audio and video chat). We will use this for almost all communication about the class, including technical questions, office hours, and (online) class sessions.

- You will need an account on [Discord](https://discord.com/).

<!-- include-exit-ticket -->
# Exit Ticket
<!-- -------------------------------------------------- -->

Once you have completed this exercise, make sure to fill out the **exit ticket survey**, [linked here](https://docs.google.com/forms/d/e/1FAIpQLSeuq2LFIwWcm05e8-JU84A3irdEL7JkXhMq5Xtoalib36LFHw/viewform?usp=pp_url&entry.693978880=e-rep00-setup-assignment.Rmd).
