---
title: "Setup: Packages"
# yaml-author
date: 2020-04-30
output: github_document
time: 5
reading: 0
---

# Setup: Packages

*Purpose*: Every time you start an analysis, you will need to *load packages*.
This is a quick warmup to get you in this habit.

*Reading*: (None)

**Note**: If you open this `.Rmd` file in RStudio you can *execute* the chunks of code (stuff between triple-ticks) by clicking on the green arrow to the top-right of the chunk, or by placing your cursor within a chunk (between the ticks) and pressing `Ctrl + Shift + Enter`. See [here](https://rmarkdown.rstudio.com/authoring_quick_tour.html) for a brief introduction to RMarakdown files. Note that in RStudio you can Shift + Click (CMD + Click) to follow a link.

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = TRUE)
```

### __q1__ Create a new code chunk and prepare to load the `tidyverse`.

In [RStudio](https://bookdown.org/yihui/rmarkdown/r-code.html) use the shortcut
`Ctrl + Alt + I` (`Cmd + Option + I` on Mac). Type the command
`library(tidyverse`).


Make sure to load packages at the *beginning* of your notebooks! This is a
best-practice.

### __q2__ Run the chunk with `library(tidyverse)`. What packages are loaded?

In
[RStudio](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts)
press `Ctrl + Alt + T` (`Cmd + Option + T` on Mac) to run the code chunk at your
cursor.


### __q3__ What are the main differences between `install.packages()` and `library()`? How often do you need to call each one?


<!-- include-exit-ticket -->
# Exit Ticket
<!-- -------------------------------------------------- -->

Once you have completed this exercise, make sure to fill out the **exit ticket survey**, [linked here](https://docs.google.com/forms/d/e/1FAIpQLSeuq2LFIwWcm05e8-JU84A3irdEL7JkXhMq5Xtoalib36LFHw/viewform?usp=pp_url&entry.693978880=e-setup01-packages-assignment.Rmd).
