# This is a basic workflow to help you get started with Actions

name: Build book and deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      
      - name: Setup
        uses: r-lib/actions/setup-r@v2
      
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: book/_bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-
          
      - name: Build site
        run: make book
        
      # Deploy the book's HTML to gh-pages branch
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/_book
