# Build the materials and bush to build branch
name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          make # Sequence the exercises
          mkdir build # Collect the build
          cp -r challenges build/.
          cp -r exercises_sequenced build/.
          rm build/exercises_sequenced/.gitignore # Ensure push of Rmd for build
          cp data-science-curriculum.Rproj build/.
          cp README.md build/.
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
